In [1]:
import numpy as np

In [17]:
l =[1,2,3,4,5]

In [11]:
arr = np.array(1)

In [4]:
type(arr)

numpy.ndarray

In [15]:
arr= np.asarray(l)

In [9]:
arr1 = np.array(([1,2,3],[2,3,4]))

In [12]:
arr.ndim

0

In [13]:
arr1.ndim

2

In [14]:
arr

array(1)

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
mat = np.matrix(l)

In [20]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr[0] = 100

In [23]:
arr

array([100,   2,   3,   4,   5])

In [25]:
a = arr

In [26]:
a

array([100,   2,   3,   4,   5])

In [27]:
b = np.copy(arr)

In [28]:
b[0] = 234

In [29]:
b

array([234,   2,   3,   4,   5])

In [30]:
a

array([100,   2,   3,   4,   5])

In [31]:
arr

array([100,   2,   3,   4,   5])

In [32]:
np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [35]:
arr

array([100,   2,   3,   4,   5])

In [36]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [37]:
arr.ndim

1

In [39]:
arr.size

5

In [40]:
arr1.size

6

In [41]:
arr.shape

(5,)

In [42]:
arr1.shape

(2, 3)

In [1]:
arr1.dtype

NameError: name 'arr1' is not defined

In [11]:
list(range(5))

[0, 1, 2, 3, 4]

In [10]:
list(range(0.4,5.4))

TypeError: 'float' object cannot be interpreted as an integer

In [4]:
import numpy as np

In [6]:
list(np.arange(0.4,5.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002]

In [7]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [8]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])