In [1]:
##Sort, Search & Counting Functions.

In [1]:
import numpy as np

In [2]:
arr = np.array([4,2,8,5,3,9,12,56])

In [3]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [4]:
np.sort(arr) 

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [7]:
np.searchsorted(arr,6) #gives you the palce that an element should be added to maintain the order of the array

5

In [9]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [11]:
np.count_nonzero(arr1) #Count number of non zero elements

6

In [12]:
np.where(arr1 > 0 ) #at what all indexes you have data > 0

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [18]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [19]:
#Numpy - Byte Swapping.

In [20]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [24]:
arr.byteswap(True)

array([ 67108864,  33554432, 134217728,  83886080,  50331648, 150994944,
       201326592, 939524096])

In [22]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [23]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [28]:
#Numpy - Copies &Views.

In [25]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [31]:
a = np.copy(arr1)

In [34]:
b = arr1.view()

In [ ]:
b = arr1

In [35]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [36]:
b[0] = 234

In [37]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [38]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [39]:
#Numpy - Matrix Library.

In [41]:
import numpy.matlib as nm

In [42]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [43]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [44]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [45]:
#Numpy - Linear Algebra

In [48]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [49]:
arr2 = np.random.randint([[5,3] , [2,5]])


In [50]:
arr1

array([[0, 1],
       [1, 4]])

In [51]:
arr2

array([[2, 2],
       [1, 2]])

In [52]:
np.dot(arr1,arr2)

array([[ 1,  2],
       [ 6, 10]])

In [53]:
arr1@arr2

array([[ 1,  2],
       [ 6, 10]])